spring:
  application:
    name: notificacoes
  kafka:
    bootstrap-servers: 'http://localhost:29092'
    consumer:
      group-id: ibank-notificacao
      auto-offset-reset: earliest

ibank:
  config:
    kafka:
      topics:
        transacao-notificacao: 'ibank.transacao-notificacao'
  jasper:
    output-path: C:/Users/user/Desktop/challenge/info/jasperfiles

server:
  port: 8086


