spring:
  application:
    name: notificacoes
  kafka:
    bootstrap-servers: 'http://localhost:29092'
    consumer:
      group-id: ibank-notificacao
      auto-offset-reset: earliest

icompras:
  config:
    kafka:
      topics:
        transacao-notificacao: 'ibank.transacao-notificacao'


server:
  port: 8086


